import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SideBar } from "@/components/sideBar";
import { Providers } from "./providers";
import { UserCheck } from "@/components/userCheck";
import { LoadingPage } from "@/components/loadingPage";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LYHS Plus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <LoadingPage />
          <main className="min-h-dvh flex">
            <UserCheck />
            <SideBar />
            <div aria-label="content" className="grow">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
