name: Notify Discord on Push

on:
  push:
    branches:
      - feature/nextjs

jobs:
  notify:
    runs-on: ubuntu-latest
    name: Notify Discord
    steps:
      - name: Notify Discord on Push
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "Code has been pushed to feature/nextjs branch. Cloudflare Pages will handle the deployment."}' \
               $DISCORD_WEBHOOK_URL
